### ISSUE TITLE
Displayed number is incorrect

### ISSUE THREAD

**Issue by mikevarela** [paulcsmith/mongoose-currency#11]
Forgive my newness.

I'm using postman to send a number, 1.25 (which is how I write it and it should represent 1 dollar and 25 cents) and save this to my database using node and mongoose/mongodb.

My model looks like

`var mongoose = require('mongoose');
require('mongoose-currency').loadType(mongoose);
var Currency = mongoose.Types.Currency;

var Schema = mongoose.Schema;

var ItemsSchema = new Schema({
    name: String,
    description: String,
    purchasePrice: {
        type: Currency
    },
    sellPrice: {
        type: Currency
    },
    active: Boolean,
    buyDate: {
        type: Date,
        default: Date.now
    },
    sellDate: Date,
    location: String,
    department: String,
    departmentItemNumber: Number

});

var ItemsModel = mongoose.model('Items', ItemsSchema);

module.exports = ItemsModel;`

But when I save this number (1.25) i get an number saved like 125, which then comes back in Angular via NG-Repeat and gets formatted with the currency pipe and is 125.00.

Angular

`<td>{{ item.purchasePrice | currency }}</td>`

wondering how to format it correctly as 1.25

Thanks so much

**Comment by paulcsmith** [comment]
Hi @mikevarela. I would take a look at the README, specifically this section: https://github.com/paulcsmith/mongoose-currency#displaying-to-end-users-views-reports-etc

It talks about how numbers are stored and how to format them. I'd go through the whole thing so you can get an idea for how it works. I hope that helps!
