### ISSUE TITLE
Moongoose 4.0

### ISSUE THREAD

**Issue by twmeier** [paulcsmith/mongoose-currency#6]
Mongoose 4.0 is now the latest version. 

Can the dependencies be updated to require mongoose "4.x" instead of "3.x"?

**Comment by nottinhill** [comment]
npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer mongoose-currency@0.0.4 wants mongoose@3.x

**Comment by paulcsmith** [comment]
I don't use Mongo anymore so I haven't worked on this much lately. If you submit a PR and all tests pass I can bump the version and submit an update.

**Comment by paulcsmith** [comment]
I appreciate the issue btw! Thank you!

**Comment by nottinhill** [comment]
Hi Paul, while trying to refactor your code I am hitting the infamous "Did you try to nest Schemas"-error of Mongoose. This also happens with version 3.9... (I know, I know)

I may release an own plugin on my repo, when we hit Mongoose 4.2 or maybe Valeri will help me develop one earlier.
